### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. 

### ISSUE THREAD

**Issue by EmptyMoon-hub** [megvii-research/DPGN#15]
Hi,
    A strange bug occurred when I ran the code to the `total_loss.backward()`
   `RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input. `
   Have you ever come across this problem

**Comment by EmptyMoon-hub** [comment]
ok, I have fixed it, the version of cudatoolkit must be 10.1

**Comment by zilunzhang** [comment]
> ok, I have fixed it, the version of cudatoolkit must be 10.1

Hi,

Great! Glad you fixed it.

Best,

DPGN teams
